eProsima/eProsima-CI

README.md, colcon.meta, depends.repos
verbatim copy of https://gitlab.intranet.eprosima.com/eProsima/fastrtps-ci
=> main initial commit with the defaults

.github/workflows/build_dev_utils.yml, .github/workflows/build_fastdds.yml, README.md, external/download-artifact/action.yml, multiplatform/fetch_dev_utils_manual/action.yml, ubuntu/fetch_dev_utils_manual/action.yml, windows/fetch_dev_utils_manual/action.yml
Workflow run can be checked [here](https://github.com/eProsima/eProsima-CI/actions/runs/6664580224)
=> Manually build dev-utils artifact

ubuntu/install_colcon/action.yml, windows/install_colcon/action.yml
This PR fixes the problem described in:
* colcon/colcon-core#602
=> [20023] Install correct empy version before installing colcon

.github/pull_request_template.md, README.md, versions.md
This PR:
1. Documents the actions added since v0.6.0 in `README.md`
2. Updates `versions.md` with the thus far missing information
3. Adds a PR submission template
- *_N/A_*: Changes are API compatible. 
- *_N/A_*: New features have been added to the `versions.md` and `README.md` files (if applicable).
s
=> [20255] Add missing documentation and PR template

external/checkout/action.yml
The external action is not correctly passing the inputs to the action per se.
- [N/A] Commit messages follow the company guidelines. 
- [N/A] New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Fix checkout external action

external/action-download-artifact/action.yml
Update _dawidd6/action-download-artifact_ action to avoid `node16` warnings in all jobs. 
- N/A New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Update action-download-artifact to v3 (node20)

multiplatform/colcon_build/action.yml, windows/colcon_build/action.yml
- (N/A) New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Remove multiplatform and windows default cmake args

multiplatform/vcs_import/action.yml, ubuntu/vcs_import/action.yml, versions.md, windows/vcs_import/action.yml
This PR adds a `skip_existing` boolean option to the `vcs_import` action.
=> [20529] Add skip_existing option to vcs_import action

.github/workflows/build_ddspipe.yml, .github/workflows/build_dev_utils.yml
=> Remove CXXFLAGS for windows

external/download-artifact/action.yml
- [N/A] New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Bump download artifact action to v4

multiplatform/vcs_import/action.yml
This PR introduces macOS vcs import command as part of the multiplatform suite
- **N/A** New features have been added to the `versions.md` and `README.md` files (if applicable).
=> [20542] Add vcs import multiplatform action for macOS case

multiplatform/install_fastdds_dependencies/action.yml, ubuntu/install_fastdds_dependencies/action.yml, windows/install_fastdds_dependencies/action.yml
=> Set default cmake version for install-fastdds-dependencies action

README.md, ubuntu/get_related_branch_from_repo/action.yml, versions.md
This PR adds a new Ubuntu action to deduce a related branch from a remote repository
=> [20694] Add Ubuntu get_related_branch_from_repo

ubuntu/get_related_branch_from_repo/action.yml
The introduced action was not taking into account tags, only branch names. 
This PR removes the `--heads` option son tags are also considered
- _N/A_ New features have been added to the `versions.md` and `README.md` files (if applicable).
=> [20705] Allow tags in `get_related_branch_from_repo` action

windows/colcon_test/action.yml
This PR corrects a conditional statement in the `colcon_test` action within the Windows CI workflow. Now, the setup script is executed correctly only when `inputs.workspace_dependencies` is not empty.
- X Commit messages follow the company guidelines. 
- _N/A_  Changes are API compatible. 
- _N/A_  New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Correct conditional statement in colcon_test action for Windows

.github/workflows/configurations/fastdds/dependencies.repos
- N/A New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Fix fastdds version to 2.x

.github/workflows/build_ddspipe.yml, .github/workflows/build_dev_utils.yml
=> Hotfix nightly artifact inputs

.github/workflows/build_dev_utils.yml, .github/workflows/configurations/dev_utils/deps_v2.repos, .github/workflows/configurations/dev_utils/deps_v3.repos
=> Enable dev-utils build for Fast DDS v3

scripts/change_actions_reference.sh, versions.md
This PR extends `change_actions_reference.sh` to also update the references within `.github`.
=> [20989] Also change .github refs with change_actions_reference.sh

multiplatform/colcon_build_test/action.yml, ubuntu/coverage_build_test_upload/action.yml
- ~~New features have been added to the `versions.md` and `README.md` files (if applicable).~~
=> Add test report artifact name input to coverage action

multiplatform/colcon_build_test/action.yml, multiplatform/colcon_build_test_flaky/action.yml, multiplatform/colcon_test/action.yml, ubuntu/colcon_test/action.yml, versions.md, windows/colcon_test/action.yml
This PR includes the colcon meta input in the colcon test action, so .metas can be taken into account in tests too.
=> [20822] Add colcon metas arg to colcon test action 

README.md, external/install_doxygen/action.yml, multiplatform/get_related_branch_from_repo/action.yml, versions.md, windows/merge_yaml_metas/action.yml
This PR introduces several improvements regarding CI procedures in different eProsima repositories.
Related PRs: 
- https://github.com/eProsima/Fast-DDS-python/pull/149 (and related backports)
List of changes that this PR introduces:
- External (multiplatform) action to install doxygen (windows oriented)
- Multiplatform action to obtain related branch from the given repository (calls existing ubuntu action)
- Windows action to merge different  .meta files into a single file
=> [21228] Improve CI workflows for different repos

.github/workflows/build_ddspipe.yml
This PR enables DDS Pipe build with Fast DDS v3
- N/A New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Enable DDS Pipe v3 build

ubuntu/install_python_packages/action.yml
=> Upgrade setuptools to 74.1.3

external/upload-artifact/action.yml
For some reason, `upload-artifact` action does not zip the symlinks anymore so the other jobs do not find the shared library object  (.so) of the generated libraries. This sets the version of this action to a version that we know works for us. 
- _N/A_ New features have been added to the `versions.md` and `README.md` files (if applicable).
=> Fix upload-artifact version to v4.4.0

multiplatform/colcon_build/action.yml, ubuntu/sphinx_docs/action.yml, versions.md
=> Fix Sphinx Docs action

versions.md
This PR introduces missing PR in the versions notes
=> Update versions with missing information

ubuntu/sphinx_docs/action.yml
Update docs job to include docs artifact name and option to disable artifact upload
=> Update docs job to include docs artifact name

external/upload-artifact/action.yml
As a result of the nightly ci failure [here](https://github.com/eProsima/Fast-DDS-python/actions/runs/12459568044/job/34776563047) and according to [upload-artifact issue 485](https://github.com/actions/upload-artifact/issues/485), we should upgrade the `upload-artifact` action to `v4.4.1`.
- **N/A** New features have been added to the `versions.md` and `README.md` files (if applicable).
=> [22522] Upgrade `upload-artifact` action to `v4.4.1`

external/upload-artifact/action.yml
Upgrading upload-artifact github action due to the following warning:
=> Upgrade upload artifact github action

ubuntu/get_related_branch_from_repo/action.yml
The `get_related_branch_from_repo` shows `line 39: [false: command not found` and thus never enters in the if that assigns the result_branch to the PR's base branch.
See an example [here](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/13374104678/job/37349244334)
=> Escape `skip_base` in `get_related_branch_from_repo`

external/test-reporter/action.yml
This PR upgrades the test reporter action and uses the forked version from eProsima that fix some issues with java-junit format. 
- __NO__ Changes are API compatible.
=> Upgrade test reporter action
